// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MockBankApi.Migrations
{
    [DbContext(typeof(StagingDbContext))]
    partial class StagingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("MockBankApi.Models.Staging", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CumulativeInflow")
                        .HasColumnType("REAL");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Staging");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e9df2ed-8299-45ad-b293-9f23cd038d0d"),
                            AccountName = "John One Doe",
                            AccountNumber = "1500643512",
                            Address = "No3 Peninsula Graden Estate",
                            City = "Ajah",
                            CumulativeInflow = 20000.0,
                            Currency = "N",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = new Guid("712f4112-7343-4b62-b8bb-2391035ffdf7"),
                            AccountName = "John Two Doe",
                            AccountNumber = "1500343511",
                            Address = "Dolphin Estate",
                            City = "Ikoyi",
                            CumulativeInflow = 200.0,
                            Currency = "N",
                            State = "Lagos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
